### ISSUE TITLE
Build failure when building example application Android image

### ISSUE THREAD

**Issue by amischler** [webfx-project/webfx-cli#3]
I have generated the example app by following the [get started documentation](https://docs.webfx.dev/#_creating_your_first_webfx_app).

The [build for the Android platform](https://docs.webfx.dev/#_android_platform) fails with the following stacktrace :

````
root@a743d391cae2:~/webfx-example# webfx build -m
[INFO] -------------< com.dooapp:webfx-example-application-gluon >-------------
[INFO] Building WebFXExample 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- gluonfx-maven-plugin:1.0.16:build (default-cli) @ webfx-example-application-gluon ---
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< com.dooapp:webfx-example-application-gluon >-------------
[INFO] Building WebFXExample 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> gluonfx-maven-plugin:1.0.16:compile (default-cli) > process-classes @ webfx-example-application-gluon >>>
[INFO]
[INFO] --- maven-enforcer-plugin:3.1.0:enforce (enforce-maven) @ webfx-example-application-gluon ---
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ webfx-example-application-gluon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ webfx-example-application-gluon ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< gluonfx-maven-plugin:1.0.16:compile (default-cli) < process-classes @ webfx-example-application-gluon <<<
[INFO]
[INFO]
[INFO] --- gluonfx-maven-plugin:1.0.16:compile (default-cli) @ webfx-example-application-gluon ---
Feb 28, 2023 9:33:17 AM com.gluonhq.substrate.util.Logger logSevere
SEVERE: Process install native-image failed with result: 3
Check the log files under null
And please check https://docs.gluonhq.com/ for more information.
Feb 28, 2023 9:33:17 AM com.gluonhq.substrate.util.Logger logInfo
INFO: Logging process [install native-image] to file: /root/webfx-example/webfx-example-application-gluon/target/gluonfx/log/process-install native-image-1677576797076.log
java.io.IOException: Error installing native-image at: /root/.webfx/cli/graalvm/graalvm-svm-java17-linux-gluon-22.1.0.1-Final/lib/installer
Please, use gu to install native-image running the following command:
$GRAALVM_HOME/bin/gu --jvm install native-image
	at com.gluonhq.substrate.model.InternalProjectConfiguration.getGraalVMBinPath(InternalProjectConfiguration.java:590)
	at com.gluonhq.substrate.model.InternalProjectConfiguration.getGraalVersion(InternalProjectConfiguration.java:126)
	at com.gluonhq.substrate.model.InternalProjectConfiguration.checkGraalVMVersion(InternalProjectConfiguration.java:468)
	at com.gluonhq.substrate.SubstrateDispatcher.<init>(SubstrateDispatcher.java:381)
	at com.gluonhq.NativeBaseMojo.createSubstrateDispatcher(NativeBaseMojo.java:159)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:53)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:298)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[INFO] Total time:  3.051 s
[INFO] Finished at: 2023-02-28T09:33:17Z
[INFO] ------------------------------------------------------------------------
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.16:compile (default-cli) on project webfx-example-application-gluon: Error: Error installing native-image at: /root/.webfx/cli/graalvm/graalvm-svm-java17-linux-gluon-22.1.0.1-Final/lib/installer
[ERROR] Please, use gu to install native-image running the following command:
[ERROR] $GRAALVM_HOME/bin/gu --jvm install native-image
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
````

The issue seems related to the installation of the native-image component of GraalVM. The logs of gu are below :

````
root@a743d391cae2:~/webfx-example# $GRAALVM_HOME/bin/gu --jvm install native-image
Downloading: Component catalog from www.graalvm.org
Could not load channel https://www.graalvm.org/component-catalog/graal-updater-component-catalog.properties: Unsupported GraalVM version: 22.1.0.1, platform linux/amd64
Error: Unsupported GraalVM version: 22.1.0.1, platform linux/amd64
````

I'm not sure whether it's an issue with webfx-cli or with the GraalVM Gluon fork. I did not find any related information to this issue. Any idea how to fix that ?

Note : I'm running the build from a Docker container, using the [maven:3.8.7-eclipse-temurin-19-focal image](https://hub.docker.com/layers/library/maven/3.8.7-eclipse-temurin-19-focal/images/sha256-4e9279a01c5116b5e2e8f9a81c07fb64444cfab8dd511d05e46147e7dfa518fb?context=explore).

**Comment by salmonb** [comment]
Thanks for reporting this.

The issue was a mistake in the way the WebFX CLI determines the GraalVM home (the structure of the downloaded file can be very different depending on the OS). It tries to find the first `/bin/` folder in the structure and then returns the parent folder as the home folder. It works in general, but in your case, it was finding `/lib/installer/bin` before `/bin/` and therefore was passing `/root/.webfx/cli/graalvm/graalvm-svm-java17-linux-gluon-22.1.0.1-Final/lib/installer` instead of `/root/.webfx/cli/graalvm/graalvm-svm-java17-linux-gluon-22.1.0.1-Final/` as the GraalVM home to Gluon. I think I fixed the problem by sorting all those bin folders before returning the first element (it was not sorted before).

Anyway you can get the fix by running `webfx bump cli`.
Let me know if that fixes your issue.

**Comment by amischler** [comment]
Thanks, the issue is fixed now!
